- plugins/jiwon/byapps/controllers/NewsManages.php
- plugins/jiwon/byapps/controllers/PointManages.php
- plugins/jiwon/byapps/controllers/newsmanages/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/newsmanages/config_list.yaml
- plugins/jiwon/byapps/controllers/newsmanages/index.htm
- plugins/jiwon/byapps/controllers/pointmanages/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/pointmanages/config_list.yaml
- plugins/jiwon/byapps/controllers/pointmanages/index.htm
- plugins/jiwon/byapps/models/NewsData.php
- plugins/jiwon/byapps/models/NewsManage.php
- plugins/jiwon/byapps/models/PointManage.php
- plugins/jiwon/byapps/models/newsmanage/columns.yaml
- plugins/jiwon/byapps/models/pointmanage/columns.yaml
- plugins/jiwon/byapps/plugin.yaml
- themes/demo/pages/newsData.htm
- themes/demo/pages/newsManage.htm
- themes/demo/partials/site/header.htm
포인트관리 모델 추가 - 데이터 출력 실패(메모리 부족 오류)
백엔드 소식관리 모델 및 메뉴 추가
백엔드 소식관리 상세 모델 추가
소식관리, 상세 페이지 추가
> 포인트, 소식관리 모델 및 페이지 추가

- plugins/jiwon/byapps/updates/builder_table_update_jiwon_byapps_home_layout.php
- plugins/jiwon/byapps/updates/builder_table_update_jiwon_byapps_home_layout_2.php
- plugins/jiwon/byapps/updates/builder_table_update_jiwon_byapps_home_layout_3.php
- plugins/jiwon/byapps/updates/version.yaml
- themes/demo/assets/css/temp.css
- themes/demo/assets/css/vendor.css
- themes/demo/assets/javascript/chart.js
- themes/demo/assets/javascript/drag.js
- themes/demo/assets/javascript/temp.js
- themes/demo/assets/javascript/util.js
- themes/demo/layouts/default.htm
- themes/demo/pages/home.htm
- themes/demo/partials/site/header.htm
메인페이지 레이아웃 사용자 별로 수정 가능(드래그 앤 드랍)
헤더 두줄로 변경
푸터 삭제
만료 예정업체 탭형식으로 변경
기타 디자인 변경
> 메인페이지 레이아웃

- themes/demo/assets/css/appdata.css
- themes/demo/pages/apkData.htm
- themes/demo/pages/apkManage.htm
- themes/demo/pages/appData.htm
- themes/demo/pages/appsList.htm
- themes/demo/pages/newsData.htm
- themes/demo/pages/newsManage.htm
- themes/demo/pages/payDetail.htm
- themes/demo/pages/payManage.htm
- themes/demo/pages/payPromoDetail.htm
- themes/demo/pages/payPromotion.htm
- themes/demo/pages/updateData.htm
- themes/demo/pages/updateManage.htm
- themes/demo/pages/usersManage.htm
- themes/demo/partials/site/aside.htm
- themes/demo/partials/site/header.htm
jumbotron부분을 header로 이동시킴
중복코드 삭제
sidebar toggle 표시 변경
> 코드정리 및  sidebar toggle 표시 변경

- themes/demo/assets/css/vendor.css
- themes/demo/layouts/default.htm
- themes/demo/pages/apkData.htm
- themes/demo/pages/apkManage.htm
- themes/demo/pages/appData.htm
- themes/demo/pages/appsList.htm
- themes/demo/pages/newsData.htm
- themes/demo/pages/newsManage.htm
- themes/demo/pages/payDetail.htm
- themes/demo/pages/payManage.htm
- themes/demo/pages/payPromoDetail.htm
- themes/demo/pages/payPromotion.htm
- themes/demo/pages/pushList.htm
- themes/demo/pages/updateData.htm
- themes/demo/pages/updateManage.htm
- themes/demo/partials/site/header.htm
- themes/demo/partials/site/navigation.htm
> breadcrumb 추가 및 업체표시부분 스타일 변경 등

- plugins/jiwon/byapps/controllers/AppsDownStats.php
- plugins/jiwon/byapps/controllers/AppsUseStats.php
- plugins/jiwon/byapps/controllers/appsdownstats/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/appsdownstats/config_list.yaml
- plugins/jiwon/byapps/controllers/appsdownstats/index.htm
- plugins/jiwon/byapps/controllers/appsusestats/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/appsusestats/config_list.yaml
- plugins/jiwon/byapps/controllers/appsusestats/index.htm
- plugins/jiwon/byapps/models/AppsDownStat.php
- plugins/jiwon/byapps/models/AppsUseStat.php
- plugins/jiwon/byapps/models/appsdownstat/columns.yaml
- plugins/jiwon/byapps/models/appsusestat/columns.yaml
- plugins/jiwon/byapps/plugin.yaml
- themes/demo/pages/appDownStat.htm
- themes/demo/pages/appUseStat.htm
- themes/demo/partials/site/navigation.htm
앱설치통계 model 추가
앱설치통계 frontend 페이지 추가
앱 이용 통계 model 추가
앱 이용 통계 frontend 페이지 추가
> 앱 설치통계, 앱 이용통계 model 및 frontend 페이지 추가

- plugins/jiwon/byapps/controllers/AppsPushDatas.php
- plugins/jiwon/byapps/controllers/MembersManages.php
- plugins/jiwon/byapps/controllers/PushOnoffStats.php
- plugins/jiwon/byapps/controllers/appspushdatas/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/appspushdatas/config_list.yaml
- plugins/jiwon/byapps/controllers/appspushdatas/index.htm
- plugins/jiwon/byapps/controllers/membersmanages/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/membersmanages/config_list.yaml
- plugins/jiwon/byapps/controllers/membersmanages/index.htm
- plugins/jiwon/byapps/controllers/pushonoffstats/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/pushonoffstats/config_list.yaml
- plugins/jiwon/byapps/controllers/pushonoffstats/index.htm
- plugins/jiwon/byapps/models/AppsPushData.php
- plugins/jiwon/byapps/models/MemberManage.php
- plugins/jiwon/byapps/models/PushOnoffStat.php
- plugins/jiwon/byapps/models/appspushdata/columns.yaml
- plugins/jiwon/byapps/models/membermanage/columns.yaml
- plugins/jiwon/byapps/models/pushonoffstat/columns.yaml
- plugins/jiwon/byapps/plugin.yaml
- themes/demo/pages/membersData.htm
- themes/demo/pages/membersManage.htm
- themes/demo/pages/pointManage.htm
- themes/demo/pages/pushOnoffStat.htm
- themes/demo/partials/site/navigation.htm
푸쉬 허용통계   model 추가
푸쉬 허용통계   frontend 페이지 추가
인증회원 관리   model 추가
앱포인트 관리 페이징   임시로 100으로 수정
인증회원관리   frontend 페이지 추가
backend 링크   추가
인증회원 관리 페이지   url 변경
인증회원관리 상세페이지   추가
인증회원 상세 페이지에   table join하고 데이터 출력
>  푸쉬 허용통계 & 인증회원관리 model, frontend 페이지 추가

- modules/cms/controllers/Index.php
- plugins/jiwon/byapps/models/PayManage.php
- plugins/jiwon/byapps/models/PaymentData.php
- plugins/jiwon/byapps/models/PromotionData.php
- plugins/jiwon/byapps/models/paymanage/columns.yaml
- plugins/jiwon/byapps/models/paymentdata/columns.yaml
- themes/demo/pages/membersData.htm
- themes/demo/pages/payDetail.htm
- themes/demo/pages/payManage.htm
- themes/demo/pages/payPromoDetail.htm
- themes/demo/pages/payPromotion.htm
- themes/demo/pages/updateManage.htm
결제관리 model 수정 및 구분,기간 등 출력형식 수정
결제관리 상세페이지 출력형식 수정
프로모션 관리 model 수정
프로모션 상세 페이지 출력방식 수정
Bug fix: backend cms의 assets/css 파일 접근시 type error 현상 fix
실수로 들어간 글자 삭제
업데이트관리 페이지 수정
> 결제관리,프로모션관리, 업데이트관리 수정 및 bug fix

- plugins/jiwon/byapps/components/paymentform/update.htm
- plugins/jiwon/byapps/plugin.yaml
- themes/demo/assets/javascript/moment.js
- themes/demo/layouts/default.htm
- themes/demo/pages/apkData.htm
- themes/demo/pages/apkManage.htm
- themes/demo/pages/appData.htm
- themes/demo/pages/membersManage.htm
- themes/demo/pages/newsData.htm
- themes/demo/pages/newsManage.htm
- themes/demo/pages/payDetail.htm
- themes/demo/pages/payManage.htm
- themes/demo/pages/pushList.htm
- themes/demo/pages/test2.htm
- themes/demo/pages/updateData.htm
- themes/demo/pages/updateManage.htm
- themes/demo/partials/site/navigation.htm
breadcrumbs   부분 수정
backend:   인증회원 관리 메뉴를 앱 관리 아래로 이동
frontend:   인증회원 관리 메뉴 추가
tabulator   테스트 + moment.js 추가
tabulator   테스트: xlsx 다운버튼 추가
tabulator   테스트: 클릭시 페이지이동 추가
결제관리 페이지에서   주석처리된 부분 제거
결제관리 목록 페이지에   tabulator 적용
> backend 메뉴 수정 및 tabulator 테스트 & 결제관리 목록에 적용

- themes/demo/assets/css/classCustom.css
- themes/demo/assets/css/temp.css
- themes/demo/layouts/default.htm
- themes/demo/pages/home.htm
- themes/demo/pages/updateManage.htm
- themes/demo/partials/site/navigation.htm
> 업데이트 관리 페이지 테이블 및 디자인 수정

- themes/demo/assets/css/appdata.css
- themes/demo/assets/css/classCustom.css
- themes/demo/assets/javascript/aside.js
- themes/demo/partials/site/aside.htm
> aside 레이아웃 css수정, 내용 추가

- plugins/jiwon/byapps/Plugin.php
- plugins/jiwon/byapps/components/Comments.php
- plugins/jiwon/byapps/components/comments/default.htm
- plugins/jiwon/byapps/controllers/Comments.php
- plugins/jiwon/byapps/controllers/comments/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/comments/config_list.yaml
- plugins/jiwon/byapps/controllers/comments/index.htm
- plugins/jiwon/byapps/models/Comment.php
- plugins/jiwon/byapps/models/comment/columns.yaml
- plugins/jiwon/byapps/plugin.yaml
- themes/demo/pages/about.htm
- themes/demo/partials/site/aside.htm
>  comments 컴포넌트 생성

- plugins/jiwon/byapps/Plugin.php
- themes/demo/assets/css/appdata.css
- themes/demo/layouts/default.htm
- themes/demo/pages/updateManage.htm
- themes/demo/partials/site/aside.htm
> aside 글씨크기 수정, 댓글창 추가

- themes/demo/layouts/default.htm
- themes/demo/pages/home.htm
- themes/demo/partials/site/navigation.htm
> 메인페이지 일부수정

- plugins/jiwon/byapps/components/datatable/default.htm
- themes/demo/layouts/list.htm
- themes/demo/pages/appsList.htm
- themes/demo/pages/updateList.htm
pageLength 100에서 50으로 변경
서비스중지 업체는 빨간색 표시 추가 테스트
datatable에 datepicker로 날짜검색 추가
안쓰는 코드 부분 주석처리
>  datatable에 datepicker로 날짜검색 추가 & 주석처리 등

- server_processing.php
- ssp.class.php
- themes/demo/pages/ajax.htm
- themes/demo/pages/appsList.htm
- themes/demo/pages/updateList.htm
- themes/demo/pages/updateList.htm.orig
- themes/demo/partials/site/navigation.htm
>  datatables ajax filtering 작업중

- themes/demo/layouts/default.htm
- themes/demo/partials/site/navigation.htm
> 히스토리 기능 추가 작업중

- plugins/jiwon/byapps/models/AppsData.php
- plugins/jiwon/byapps/models/PaymentData.php
- plugins/jiwon/byapps/models/appsdata/columns.yaml
- plugins/jiwon/byapps/models/paymentdata/columns.yaml
- themes/demo/assets/javascript/chart.js
- themes/demo/assets/javascript/drag.js
- themes/demo/layouts/default.htm
- themes/demo/pages/home.htm
기존 chart data와 불러오는 부분 개별로 분리
앱 통계 쿼리 데이터 정리 + 원래 php 쿼리 주석에 추가함
MA 통계 불러오는 쿼리 정리
주문요청현황 개별 div sortable 추가
> 앱 통계, MA통계 데이터 불러오는 부분과 주문요청현황 부분 sortable 추가

- plugins/jiwon/byapps/Plugin.php
- plugins/jiwon/byapps/components/ChartData.php
- plugins/jiwon/byapps/components/ExpiredData.php
- plugins/jiwon/byapps/components/chartdata/default.htm
- plugins/jiwon/byapps/components/expireddata/default.htm
- plugins/offline/sitesearch/components/searchresults/pagination.htm
- plugins/offline/sitesearch/components/searchresults/searchresult.htm
- themes/demo/assets/javascript/chart.js
- themes/demo/layouts/default.htm
- themes/demo/pages/home.htm
검색결과 스타일 및 검색결과 pagination 스타일 변경
home.htm에 있던 차트 데이터를 컴포넌트(chartData)로 등록
home.htm에 있던 만료예정업체 데이터를 컴포넌트(expiredData)로 등록
> 검색결과 스타일 변경 및 기존 home에 있던 함수들을 컴포넌트로 등록

- plugins/jiwon/byapps/controllers/additionalservices/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/additionalservices/config_list.yaml
- plugins/jiwon/byapps/controllers/additionalservices/index.htm
- plugins/jiwon/byapps/controllers/maservices/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/maservices/config_list.yaml
- plugins/jiwon/byapps/controllers/maservices/index.htm
- plugins/jiwon/byapps/controllers/membersmanages/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/membersmanages/config_list.yaml
- plugins/jiwon/byapps/controllers/membersmanages/index.htm
- plugins/jiwon/byapps/controllers/testermanages/_list_toolbar.htm
- plugins/jiwon/byapps/controllers/testermanages/config_list.yaml
- plugins/jiwon/byapps/controllers/testermanages/index.htm
- plugins/jiwon/byapps/models/additionalservice/columns.yaml
- plugins/jiwon/byapps/models/maservice/columns.yaml
- plugins/jiwon/byapps/models/membermanage/columns.yaml
- plugins/jiwon/byapps/models/testermanage/columns.yaml
- themes/demo/assets/css/appdata.css
- themes/demo/assets/javascript/aside.js
- themes/demo/layouts/default.htm
- themes/demo/pages/appsDetail.htm
- themes/demo/partials/site/aside.htm
> 사이드바 수정, 앱상세페이지 수정

- plugins/jiwon/byapps/Plugin.php
- plugins/jiwon/byapps/components/ChartData.php
- plugins/jiwon/byapps/components/ExpiredData.php
- themes/demo/pages/home.htm
만료 예정업체 탭 부분 재 작업
만료예정업체 스타일 약간 변경
push인증서 만료 데이터 추가
> 만료 예정업체 탭 부분 재 작업 및 Push인증서 만료 데이터 추가

- themes/demo/pages/appsDetail.htm
> google api키 제거

- package-lock.json
> fix the vulnerable dependency
